blueprint:
  name: Charge battery when electricity is cheap
  description: >
    Triggers an EOS optimization when the current electricity price falls below
    a configurable threshold (default: 70% of the daily average).
  domain: automation
  input:
    price_sensor:
      name: Price Forecast Sensor
      description: The EOS price forecast sensor entity.
      selector:
        entity:
          domain: sensor
          integration: eos_ha
    threshold_factor:
      name: Threshold Factor
      description: >
        Trigger when current price is below (average × this factor).
        Default 0.7 means 70% of average.
      default: 0.7
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.05
          mode: slider

trigger:
  - platform: state
    entity_id: !input price_sensor

condition:
  - condition: template
    value_template: >
      {% set prices = state_attr(trigger.entity_id, 'forecast') %}
      {% if prices and prices | length > 0 %}
        {% set avg = prices | sum / prices | length %}
        {% set current = states(trigger.entity_id) | float(0) %}
        {{ current < avg * (input.threshold_factor | float(0.7)) }}
      {% else %}
        false
      {% endif %}

action:
  - service: eos_ha.optimize_now
